---
name: fuzz-and-race

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.go"
      - go.*

permissions: {}

concurrency:
  group: fuzz-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  fuzz-and-race:
    timeout-minutes: 10
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25.7"]
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore fuzz cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/go-build/fuzz
          key: fuzz-${{ runner.os }}-${{ hashFiles('**/*_fuzz_test.go') }}
          restore-keys: |
            fuzz-${{ runner.os }}-

      - name: Run race condition tests
        run: make test-race

      - name: Run fuzz tests
        run: make test-fuzz
